# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-22 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180922_2158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('created',), 'verbose_name': 'Autor'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ('created',), 'verbose_name': 'M\xfasica'},
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Author'),
        ),
    ]
