# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-22 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180922_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
