# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 05:04
from __future__ import unicode_literals

import api.models.mass_models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180922_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MassMoment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_name', models.CharField(choices=[('EN', 'CANTO DE ENTRADA'), ('EP', 'EM NOME DO PAI'), ('AP', 'ATO PENITENCIAL'), ('GL', 'GL\xd3RIA'), ('SM', 'SALMO'), ('AL', 'ALELUIA'), ('OF', 'OFERT\xd3RIO'), ('ST', 'SANTO'), ('PC', 'PAZ DE CRISTO'), ('CD', 'CORDEIRO DE DEUS'), ('CM', 'COMUNH\xc3O'), ('PC', 'P\xd3S COMUNH\xc3O'), ('NS', 'ORA\xc7\xc3O DE NOSSA SENHORA'), ('CO', 'CANTO FINAL'), ('OT', 'OUTROS')], max_length=2, verbose_name='Momento da Missa')),
                ('reflection', models.TextField(blank=True, null=True, verbose_name='reflex\xe3o')),
            ],
            options={
                'verbose_name': 'Momento da missa',
                'verbose_name_plural': 'Momentos da missa',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name=api.models.mass_models.Author),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nome do autor'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Author', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(verbose_name='Letra'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Nome da m\xfasica'),
        ),
        migrations.AddField(
            model_name='massmoment',
            name='songs',
            field=models.ManyToManyField(to='api.Song', verbose_name='M\xfasicas do momento'),
        ),
    ]
