# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180923_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mass',
            name='massMoments',
        ),
        migrations.AddField(
            model_name='massmoment',
            name='mass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Mass'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='day',
            field=models.DateField(verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Sobre a missa'),
        ),
    ]
