# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180923_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link do YouTube'),
        ),
    ]
