# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-04 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180923_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='mass',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='massmoment',
            name='mass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mass_moments', to='api.Mass'),
        ),
    ]
