# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-04 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181004_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massmoment',
            old_name='moment_name',
            new_name='moment_type',
        ),
    ]
